Space Calculator Inputs: HTTP Flow
Yammayap/widgets.workplacefutures.com pull request #13
Opened 2024-02-02 12:37 UTC by jimleeder123

This is the inputs page with no styling, dummy text and the fields listed out. I have created some view components for the text inputs and selects. 

I thought about doing one select component for an enum select but I have done them separately for each enum since we might want to add something to a specific field but not to another. Perhaps an alternative could be to have another abstract enum select class?

2024-02-02 12:38 UTC, jimleeder123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Space calculator inputs: HTTP flow](https://trello.com/c/U9cKmd7W/26-space-calculator-inputs-http-flow)

2024-02-02 17:18 UTC, gbuckingham89 requested changes
We're going in the right direction - I've left comments for a few small tweaks  - but lets have a chat about the view components too;

- There's a much better way to handle all the attributes
- Let's avoid having all individual components for each enum - especially as they'll only ever be used once! 
- Might be worth considering having a form label component too
- File / directory structure

2024-02-02 17:18 UTC, gbuckingham89 commented on resources/views/components/header.blade.php
> +                <img src="/{{ $tenant->logoFilePath() }}" alt="{{ $tenant->label() }}" />
Rather than just adding the `/` here, let's fix this in the tenant enum - I'd suggest;

- Renaming the method to `logoFileUrl()`
- Changing its return to `return asset('/img/tenants/logos/' . $this->logo());`

2024-02-02 17:18 UTC, gbuckingham89 commented on app/Http/Controllers/Web/SpaceCalculator/InputsController.php
> +        // todo: discuss meta title - probably defer, this is ok for now but doesn't seem like a final title
I'd say it's good enough for now!

2024-02-02 17:18 UTC, gbuckingham89 commented on app/Http/Requests/Web/SpaceCalculator/PostSpaceCalculatorInputsRequest.php
The "YY way" is to name our request classes the same as the route method they're for - so this should be named `PostIndexRequest`

2024-02-02 17:18 UTC, gbuckingham89 commented on app/Http/Requests/Web/SpaceCalculator/PostSpaceCalculatorInputsRequest.php
> +            'desk_percentage' => ['required', 'numeric', 'min:0'],
- Can we swap `integer` for `numeric` - we don't want decimals!
- Can we add a `max` rule that stops people entering a value higher than the DB schema allows

2024-02-02 17:18 UTC, gbuckingham89 commented on resources/views/web/space-calculator/inputs.blade.php
> +        {{ csrf_field() }}
Not a big difference, but I think the "Laravel way" has moved to using the blade directive (`@csrf`) rather than echoing the field.

2024-02-05 09:42 UTC, jimleeder123 commented on app/View/Components/Errors.php
Done

2024-02-05 09:45 UTC, jimleeder123 commented on resources/views/components/errors.blade.php
Replaced the if with another if - `@if($this->shouldRender())` - is this what you meant?

2024-02-05 09:48 UTC, jimleeder123 commented on resources/views/components/header.blade.php
> +                <img src="/{{ $tenant->logoFilePath() }}" alt="{{ $tenant->label() }}" />
Done

2024-02-05 09:51 UTC, gbuckingham89 commented on resources/views/components/errors.blade.php
Not quite - we won't need an if statement in the view at all if the component class has a `shouldRender()` method; https://laravel.com/docs/10.x/blade#rendering-components

2024-02-05 09:56 UTC, jimleeder123 commented on resources/views/web/space-calculator/inputs.blade.php
> +        {{ csrf_field() }}
Done

2024-02-05 10:14 UTC, jimleeder123 commented on app/View/Components/Errors.php
This is actually not working. The error bag is empty when I do a `dd()` in the view component class. Also I've had a look at Tower's error component class which is not doing a `shouldRender()` so let's discuss this later

2024-02-05 10:15 UTC, jimleeder123 commented on app/Http/Requests/Web/SpaceCalculator/PostSpaceCalculatorInputsRequest.php
Done

2024-02-05 10:16 UTC, jimleeder123 commented on app/Http/Requests/Web/SpaceCalculator/PostSpaceCalculatorInputsRequest.php
> +            'desk_percentage' => ['required', 'numeric', 'min:0'],
I have made the max values for the integer fields `2147483647` which is the max amount the DB field can hold but should we come up with more sensible numbers?

2024-02-05 17:26 UTC, gbuckingham89 approved these changes
Looks great, solid foundation ready for more forms in future! 🚀

2024-02-06 09:52 UTC, merged