Space Calculator Inputs: Capture data
Yammayap/widgets.workplacefutures.com pull request #15
Opened 2024-02-06 10:50 UTC by jimleeder123

This is for the posting / capturing of input data. This branch was created from the HTTP branch after it went into a PR so some of the commits from that branch are visible here. The recent changes from that branch and from the recently merged PR are in here too via the test branch.

2024-02-06 10:51 UTC, jimleeder123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Space calculator inputs: Capture data](https://trello.com/c/UB7zo6WW/54-space-calculator-inputs-capture-data)

2024-02-06 11:08 UTC, gbuckingham89 requested changes
Great start using actions - we're on the right path.

One small general comment, as they typically represent "crud" actions, it's generally best to group the actions by "model" rather than "feature".

2024-02-06 11:08 UTC, gbuckingham89 commented on tests/Unit/Actions/SpaceCalculator/CreateAndGetEnquiryTest.php
> +    public function test_enquiry_is_created_and_returned_for_auth_user(): void
When we change the action, we'll have to re-work this test a little - we shouldn't have to actually authenticate a user!

2024-02-06 11:08 UTC, gbuckingham89 commented on tests/TestCase.php
> +    protected function authenticateUser(User $user = null): User
Nice work adding this helper!

2024-02-06 11:08 UTC, gbuckingham89 commented on app/Http/Controllers/Web/SpaceCalculator/InputsController.php
> +            // todo: is it better to pass in enums here, or pass in strings and run "from()" functions in the action?
We usually want to be as strict as possible with types - so passing in the enums as you are is spot on! 👍

2024-02-06 11:08 UTC, gbuckingham89 commented on app/Http/Controllers/Web/SpaceCalculator/InputsController.php
> +            $request->input('total_people'),
As these are integers, we could use the `$request->integer()` method so we actually pass an `int` rather than a `string`.

2024-02-06 11:08 UTC, gbuckingham89 commented on app/Actions/SpaceCalculator/CreateInputAction.php
> +    public function handle(
Small thing, but I'd have `$enquiry` as the first parameter, as the `SpaceCalculatorInput` will "belong" to the `Enquiry`.

2024-02-06 11:08 UTC, gbuckingham89 commented on app/Actions/SpaceCalculator/CreateInputAction.php
> +    public function handle(
Can we review the casing here - we should be sticking to `camelCase` for variables; https://dev-handbook.yammayap.com/php/coding-standards/

2024-02-06 11:33 UTC, jimleeder123 commented on app/Actions/SpaceCalculator/CreateAndGetEnquiryAction.php
Pass in widget too

2024-02-06 13:30 UTC, jimleeder123 commented on app/Actions/SpaceCalculator/CreateAndGetEnquiryAction.php
Done

2024-02-06 13:42 UTC, jimleeder123 commented on app/Actions/SpaceCalculator/CreateInputAction.php
> +        $input->enquiry_id = $enquiry->id;
Done

2024-02-06 13:54 UTC, jimleeder123 commented on tests/Unit/Actions/SpaceCalculator/CreateAndGetEnquiryTest.php
> +    public function test_enquiry_is_created_and_returned_for_auth_user(): void
Done, it seems strange to do this because we intend it to be the authenticated user but we can pass in any user to the action so makes sense!

2024-02-06 13:55 UTC, jimleeder123 commented on app/Http/Controllers/Web/SpaceCalculator/InputsController.php
> +            $request->input('total_people'),
Done

2024-02-06 13:55 UTC, jimleeder123 commented on app/Actions/SpaceCalculator/CreateInputAction.php
> +    public function handle(
Done

2024-02-06 13:57 UTC, jimleeder123 commented on app/Actions/SpaceCalculator/CreateInputAction.php
> +    public function handle(
Done

2024-02-06 14:54 UTC, gbuckingham89 requested changes
This is looking good, almost there - just a couple of tweaks to the tests and I think we'll be good to go!

2024-02-06 14:54 UTC, gbuckingham89 commented on tests/Unit/Actions/Enquiries/CreateActionTest.php
> +class CreateActionTest extends TestCase
We shouldn't be using the `TenantManager` in the tests - especially passing in a `request()`. 

The `CreateAction` doesn't care where the `Tenant` comes from.

So, we can just pass a`Tenant::SOMETHING` directly to the `CreateAction`.

2024-02-06 14:54 UTC, gbuckingham89 commented on tests/Unit/Actions/SpaceCalculatorInputs/CreateActionTest.php
> +        $this->assertNotNull($input->enquiry_id);
Rather than just asserting that the input has an enquiry ID - we could assert that is the correct one using the `is()` Eloquent method;

```php
$this->assertTrue($input->enquiry->is($enquiry))
```

2024-02-06 14:59 UTC, jimleeder123 commented on tests/Unit/Actions/Enquiries/CreateActionTest.php
> +class CreateActionTest extends TestCase
Done

2024-02-06 15:00 UTC, jimleeder123 commented on tests/Unit/Actions/SpaceCalculatorInputs/CreateActionTest.php
> +        $this->assertNotNull($input->enquiry_id);
Done

2024-02-07 14:26 UTC, gbuckingham89 approved these changes
Looks perfect! 👌

2024-02-07 14:28 UTC, merged