Web Summary Output
Yammayap/widgets.workplacefutures.com pull request #22
Opened 2024-02-09 16:51 UTC by jimleeder123

I would like to discuss mocking the calculator class in the feature tests but apart from that this is all done. There are questions in the files in comments as before. 

With the middleware I tried to think of a way to get a policy working but thought it was better to just do `Auth::check()` and then the rest of the logic after this. I could've got it working on the route but it doesn't seem sensible to do a redirect in a policy.

With the view I've got all of the outputs showing as view components even though they are all empty values.

2024-02-09 17:06 UTC, jimleeder123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Present web summary output](https://trello.com/c/dJkcz7Xb/27-present-web-summary-output)

2024-02-11 15:32 UTC, gbuckingham89 requested changes
Looks good - I think I've replied to all your questions + have added some other suggestions.

I think the middleware is spot on! Yeah, I don't think you can't return a redirect from a policy anyway.

Yep, placeholder views are good enough for now until we get the designs!

2024-02-11 15:32 UTC, gbuckingham89 commented on app/Http/Controllers/Web/SpaceCalculator/InputsController.php
> +        return redirect()->route('web.space-calculator.outputs.index', $input->uuid);
We can just pass the model - no need to pass the UUID

2024-02-11 15:32 UTC, gbuckingham89 commented on config/widgets/space-calculator.php
> +    'outputs-summary-session-id-key' => 'space-calculator-inputs-uuid',
I think this is a good place, but I'd probably go with a shorter name - maybe `input-session-key`

2024-02-11 15:32 UTC, gbuckingham89 commented on app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
> +    }
In controllers, it's generally better to use inject into the route methods rather than the constructor.

2024-02-11 15:32 UTC, gbuckingham89 commented on app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
> +            ->first();
No need for all this if we just pass the SpaceCalculatorInput though the route anyway.

2024-02-11 15:32 UTC, gbuckingham89 commented on app/Http/Middleware/SpaceCalculatorOutputsSummaryAuthCheck.php
> +            // todo: might be good to do Laraflash messages here later
Good thinking, but I wouldn't worry for now - let's keep it simple.

2024-02-11 15:32 UTC, gbuckingham89 commented on app/Http/Middleware/SpaceCalculatorOutputsSummaryAuthCheck.php
> +            // todo: might be good to do a Laraflash message here later
Good thinking, but I wouldn't worry for now - let's keep it simple.

2024-02-11 15:32 UTC, gbuckingham89 commented on app/Http/Kernel.php
> +            \App\Http\Middleware\SpaceCalculatorOutputsSummaryAuthCheck::class,
Agreed a shorter name might be a good idea! Maybe `guard_space_calculator_output` ? If we do rename it, lets rename the class to keep that similar too!

2024-02-11 15:32 UTC, gbuckingham89 commented on resources/views/components/space-calculator/outputs/questions.blade.php
> +    <ul> {{-- todo: discuss wording of this - perhaps defer until we have designs? (Trying to keep this short for now) --}}
Agreed, good enough for now!

2024-02-11 15:32 UTC, gbuckingham89 commented on resources/views/web/space-calculator/outputs.blade.php
> +      <h2>View Detailed Results</h2>
"Get results PDF"

2024-02-11 15:32 UTC, gbuckingham89 commented on resources/views/web/space-calculator/outputs.blade.php
> +      <button type="button">View Detailed Results</button>
"Get results PDF"

2024-02-11 15:32 UTC, gbuckingham89 commented on tests/Feature/Http/Web/SpaceCalculator/InputsController/PostIndexTest.php
> +        );
We shouldn't be calling the session directly in a feature test - we can use `->assertSessionHas('key', 'value')` on the response instead.

2024-02-11 15:32 UTC, gbuckingham89 commented on tests/Feature/Http/Web/SpaceCalculator/InputsController/PostIndexTest.php
> +        $this->assertNull(Session::get(config('widgets.space-calculator.outputs-summary-session-id-key')));
We shouldn't be calling the session directly in a feature test - we can use `->assertSessionMissing('key')` on the response instead.

2024-02-11 15:32 UTC, gbuckingham89 commented on tests/Feature/Http/Web/SpaceCalculator/InputsController/PostIndexTest.php
> +        $this->assertNull(Session::get(config('widgets.space-calculator.outputs-summary-session-id-key')));
We shouldn't be calling the session directly in a feature test - we can use `->assertSessionMissing('key')` on the response instead.

2024-02-11 15:32 UTC, gbuckingham89 commented on tests/Feature/Http/Web/SpaceCalculator/InputsController/PostIndexTest.php
> +        $this->assertNull(Session::get(config('widgets.space-calculator.outputs-summary-session-id-key')));
We shouldn't be calling the session directly in a feature test - we can use `->assertSessionMissing('key')` on the response instead.

2024-02-11 15:32 UTC, gbuckingham89 commented on tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetIndexTest.php
> +            ->assertViewIs('web.space-calculator.outputs');
Most of the tests helpers are "fluent" so we can use method changing to make these tests a little easier to read e.g.

```php
$this->withSession([config('widgets.space-calculator.outputs-summary-session-id-key') => $inputs->uuid])
  ->get(route('web.space-calculator.outputs.index', $inputs->uuid))
  ->assertOk()
  ->assertViewIs('web.space-calculator.outputs');
```

2024-02-11 15:32 UTC, gbuckingham89 commented on tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetIndexTest.php
Great set of tests! Remind me I'll explain the calculator mocking.

2024-02-12 09:21 UTC, jimleeder123 commented on app/Http/Controllers/Web/SpaceCalculator/InputsController.php
> +        return redirect()->route('web.space-calculator.outputs.index', $input->uuid);
Done

2024-02-12 09:21 UTC, jimleeder123 commented on routes/web.php
> +        Route::get('{uuid}/summary', [Web\SpaceCalculator\OutputsController::class, 'getIndex'])
This is causing a 404?

2024-02-12 09:23 UTC, jimleeder123 commented on config/widgets/space-calculator.php
> +    'outputs-summary-session-id-key' => 'space-calculator-inputs-uuid',
Done

2024-02-12 09:24 UTC, jimleeder123 commented on app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
> +    }
To be discussed

2024-02-12 09:27 UTC, jimleeder123 commented on app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
> +            ->first();
To be discussed

2024-02-12 09:28 UTC, jimleeder123 commented on app/Http/Middleware/SpaceCalculatorOutputsSummaryAuthCheck.php
> +            // todo: might be good to do Laraflash messages here later
Leaving the notes as reminders for later

2024-02-12 09:29 UTC, jimleeder123 commented on app/Http/Middleware/SpaceCalculatorOutputsSummaryAuthCheck.php
> +            // todo: might be good to do a Laraflash message here later
Leaving the notes as reminders for later

2024-02-12 09:31 UTC, jimleeder123 commented on app/Http/Kernel.php
> +            \App\Http\Middleware\SpaceCalculatorOutputsSummaryAuthCheck::class,
Done, thanks

2024-02-12 09:32 UTC, jimleeder123 commented on resources/views/web/space-calculator/outputs.blade.php
> +      <h2>View Detailed Results</h2>
Changed

2024-02-12 09:32 UTC, jimleeder123 commented on resources/views/web/space-calculator/outputs.blade.php
> +      <button type="button">View Detailed Results</button>
Changed

2024-02-12 09:37 UTC, jimleeder123 commented on tests/Feature/Http/Web/SpaceCalculator/InputsController/PostIndexTest.php
> +        );
This only works if I put `$response = $this->post......` instead of just `$this->assertSessionHas` but got it working now

2024-02-12 09:39 UTC, jimleeder123 commented on tests/Feature/Http/Web/SpaceCalculator/InputsController/PostIndexTest.php
> +        $this->assertNull(Session::get(config('widgets.space-calculator.outputs-summary-session-id-key')));
Done similar to last point

2024-02-12 09:40 UTC, jimleeder123 commented on tests/Feature/Http/Web/SpaceCalculator/InputsController/PostIndexTest.php
> +        $this->assertNull(Session::get(config('widgets.space-calculator.outputs-summary-session-id-key')));
Done similar to last point

2024-02-12 09:42 UTC, jimleeder123 commented on tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetIndexTest.php
> +            ->assertViewIs('web.space-calculator.outputs');
Done

2024-02-12 09:55 UTC, jimleeder123 commented on routes/web.php
> +        Route::get('{uuid}/summary', [Web\SpaceCalculator\OutputsController::class, 'getIndex'])
Done

2024-02-12 09:56 UTC, jimleeder123 commented on app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
> +    }
Done

2024-02-12 09:57 UTC, jimleeder123 commented on app/Http/Controllers/Web/SpaceCalculator/OutputsController.php
> +            ->first();
Done

2024-02-12 10:15 UTC, jimleeder123 commented on tests/Feature/Http/Web/SpaceCalculator/OutputsController/GetIndexTest.php
Done

2024-02-12 10:59 UTC, gbuckingham89 approved these changes
Looks good 👍

2024-02-12 11:51 UTC, merged