Tenants
Yammayap/widgets.workplacefutures.com pull request #3
Opened 2024-01-29 16:05 UTC by jimleeder123

This is for the set up of the tenant manager and identifying which tenant you are on using the `ref` variable in the URL query string.

If the var is set to a valid tenant enum then that enum is saved to the session. It falls back to the WFG enum by default.

2024-01-29 17:37 UTC, gbuckingham89 requested changes
Overall nice job, especially using the container and mocking for the first time 🚀! Just a few small bits to tidy up.

Also, I know the company logos are only temporary but can we give some thought about where we store them - maybe moving the `tenants` directory inside a new `public/img` directory would be a good idea, so eventually all images live in one place?

_I know there is a lot to take in with the container and mocking - but the more we do it, the more it will become clearer! But do say if something doesn't make sense and I'll try to explain better._

2024-01-29 17:37 UTC, gbuckingham89 commented on app/Enums/TenantEnum.php
Can we we drop the `Enum` prefix from the class name? (https://dev-handbook.yammayap.com/php/best-practices/)

2024-01-29 17:37 UTC, gbuckingham89 commented on app/Services/TenantManager/TenantManager.php
No much of an issue here as it's only a relatively small class, but grumpy reviewer would question the order of the method definitions - we'd usually go alphabetical / or public then private, sub-sorted by alphabetical too - something to consider for future classes.

2024-01-29 17:37 UTC, gbuckingham89 commented on resources/css/app.css
Grumpy reviewer would say this doesn't relate to this PR, but doesn't mater too much.

2024-01-29 17:37 UTC, gbuckingham89 commented on resources/views/skeleton.blade.php
> +    <meta name="robots" content=”noindex,nofollow”>
Can we remove this line - the robots tag is controlled can be / should be set by the SEO package.

2024-01-29 17:37 UTC, gbuckingham89 commented on resources/views/skeleton.blade.php
> +    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
We don't know we'll be using this - so can we get rid for now please!

_So we don't forget exists and end up loading unnesscary things!_

2024-01-29 17:37 UTC, gbuckingham89 commented on resources/views/skeleton.blade.php
Again, grumpy reviewer would question why it's in this PR, but happy to leave it for now if we tidy it up!

2024-01-29 17:37 UTC, gbuckingham89 commented on routes/web.php
> +use App\Http\Controllers\DashboardController;
Unused import! 

Remind me and I'll show you a PHPStorm setting that automatically tidies these up :)

2024-01-30 09:33 UTC, jimleeder123 commented on app/Enums/TenantEnum.php
Done

2024-01-30 09:37 UTC, jimleeder123 commented on app/Services/TenantManager/TenantManager.php
Have done this so it's public then private and sorted alphabetically.

2024-01-30 09:38 UTC, jimleeder123 commented on resources/css/app.css
The file has been cleared back to it's original state, this was just something to get it working while I was doing the temp test view for visual purposes

2024-01-30 09:39 UTC, jimleeder123 commented on resources/views/skeleton.blade.php
> +    <meta name="robots" content=”noindex,nofollow”>
Removed

2024-01-30 09:39 UTC, jimleeder123 commented on resources/views/skeleton.blade.php
> +    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
Removed

2024-01-30 09:40 UTC, jimleeder123 commented on resources/views/skeleton.blade.php
It was to get the temp test view working. It is mostly copied from MPMR and have tidied it up

2024-01-30 09:40 UTC, jimleeder123 commented on routes/web.php
> +use App\Http\Controllers\DashboardController;
Removed

2024-01-30 09:51 UTC, gbuckingham89 approved these changes
Looks good - nice work! Let's get the first "real" PR for widgets merged 🥳🍾

2024-01-30 09:59 UTC, merged