Magic Link Endpoint
Yammayap/widgets.workplacefutures.com pull request #37
Opened 2024-02-20 15:57 UTC by jimleeder123

This work is for the process that happens when someone clicks the link in the email sent in the `Actions\MagicLinks\SendAction` action class.

I wrote the description for this Trello card originally so if you have anything to add to what this could do let me know. I saw your comment about letting authenticated users click the link and switch users so I have done that. They will be clicking a signed URL and having their IP address checked so this will work. 

I have left some questions in comments as normal.

2024-02-20 19:32 UTC, gbuckingham89 requested changes
Good first attempt - but we need to rethink the architecture a little - as explained on the comments on the `LoginAction`, we don't want to be doing as much as we are in there.

This might be my fault - I could have probably explained actions better when we started. 

Let me know if you want to discuss it though.

2024-02-20 19:32 UTC, gbuckingham89 commented on app/Actions/MagicLinks/LoginAction.php
We need to have a but of a re-think with this action - they should only really be doing create / update / delete actions on models.

They shouldn't be doing anything with session / auth or returning redirects. Actions should be callable almost anywhere - imagine if we called an action from a cron task or queued job - interacting with the session / auth is irrelevant.

You'll see some comments below for what should be moved out. Once we done that, it might be best to rename this slightly - maybe `MarkAsAuthenticated`?

2024-02-20 19:32 UTC, gbuckingham89 commented on app/Actions/MagicLinks/LoginAction.php
> +    public function handle(string $ipAddress, MagicLink $magicLink): RedirectResponse
Not a big deal, but best practice is to pass in the model / object we're "operating" on first, then any additional arguments needed.

2024-02-20 19:32 UTC, gbuckingham89 commented on app/Actions/MagicLinks/LoginAction.php
> +        }
Let's move this into the controller.

2024-02-20 19:32 UTC, gbuckingham89 commented on app/Actions/MagicLinks/LoginAction.php
> +            return redirect($magicLink->getIntendedUrl());
Let's move this into the controller.

2024-02-20 19:32 UTC, gbuckingham89 commented on app/Actions/MagicLinks/LoginAction.php
> +        if ($magicLink->isValid($ipAddress)) {
Let's move this logic into a middleware - maybe `VerifyMagicLink`?

2024-02-20 19:32 UTC, gbuckingham89 commented on app/Actions/MagicLinks/LoginAction.php
> +        return redirect(route('web.home.index'));
Instead of returning redirects, let's either return nothing, or the `MagicLink` model.

2024-02-20 19:32 UTC, gbuckingham89 commented on app/Http/Controllers/Web/AuthController.php
> +        return LoginAction::run($request->ip(), $magicLink);
See comments for the `LogicAction` - we'll be moving some logic into here!

2024-02-20 19:32 UTC, gbuckingham89 commented on routes/web.php
> +    ->middleware('signed')
See comments for the `LogicAction` - we'll be adding another middleware here!

2024-02-20 19:32 UTC, gbuckingham89 commented on app/Models/MagicLink.php
> +        'authenticated_at' => 'immutable_datetime',
Well spotted!

2024-02-20 19:32 UTC, gbuckingham89 commented on app/Models/MagicLink.php
> +    }
Nice idea, but strictly speak this shouldn't really be the responsibility of the model - they're just here to represent data. Moving this logic that determines the location for the redirect into the controller would be better.

2024-02-20 19:32 UTC, gbuckingham89 commented on app/Models/MagicLink.php
> +    }
As per comments in the `LogicAction`, let's move this into a middleware. That will also have direct access to a `Request` object, so won't need the IP address passing in.

2024-02-20 19:32 UTC, gbuckingham89 commented on app/Notifications/MagicLinkNotification.php
> +            ->subject('[' . $this->magicLink->requested_at->format('d/m/Y H:i') . '] - Log in to '
Yep, really nice thought - I can't think of anything better than a date/timestamp either, but I'd maybe move it to the end of the subject rather than the start. That way if the subject gets truncated (e.g. in a notification), the login part isn't lost.

But we do need to be careful of is timezones! 

The `requested_at` timestamp in the DB / on the model will be in UTC. So it will look OK to UK users at the moment, but when the clocks change to BST and we're an hour ahead of UTC, this will be wrong!

We already have a `formatDateTime()` method in the `Helpers` class that localises the Carbon instance to the right timezone so we could use that here, especially as it also does the formatting.

That might be a good candidate for refactoring in the future too - I think it's probably better to have one helper that localises the Carbon instance to the right timezone, and then have an enum that has out "common" formats defined (e.g. long and short date formats, both with and without times etc), that we can pass to the `format()` method for consistency.

2024-02-20 19:32 UTC, gbuckingham89 commented on tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
Lets fix-up the architecture in the controller / middleware / action, then revisit the tests here.

2024-02-20 19:32 UTC, gbuckingham89 commented on tests/Unit/Actions/MagicLinks/LoginActionTest.php
Lets fix-up the architecture in the controller / middleware / action - this test itself should then be simpler!

2024-02-20 19:32 UTC, gbuckingham89 commented on tests/Unit/Models/MagicLinkTest.php
As we're moving both things being tested here, we won't need this test file anymore.

2024-02-21 10:06 UTC, jimleeder123 commented on app/Actions/MagicLinks/LoginAction.php
> +    public function handle(string $ipAddress, MagicLink $magicLink): RedirectResponse
Done and existing tests / functions changed to fit

2024-02-21 10:06 UTC, jimleeder123 commented on app/Actions/MagicLinks/LoginAction.php
> +        }
Done

2024-02-21 10:08 UTC, jimleeder123 commented on app/Actions/MagicLinks/LoginAction.php
> +            return redirect($magicLink->getIntendedUrl());
Done

2024-02-21 10:20 UTC, jimleeder123 commented on app/Actions/MagicLinks/LoginAction.php
> +        if ($magicLink->isValid($ipAddress)) {
I have done this, got a question I've left in the comments which is.... (not yet committed / pushed at this time)

In the middleware, if the magic is "not valid" - is it better to redirect away or do a 403? 

(I am presuming a redirect is better?)

2024-02-21 10:35 UTC, jimleeder123 commented on app/Models/MagicLink.php
> +    }
I have moved this into the controller. My thoughts for doing this was to reduce the amount of code in the controller and in case we need it elsewhere in the future (though we don't need it elsewhere at the moment).

2024-02-21 10:36 UTC, jimleeder123 commented on app/Models/MagicLink.php
> +    }
Done as per other comments

2024-02-21 10:42 UTC, jimleeder123 commented on app/Notifications/MagicLinkNotification.php
> +            ->subject('[' . $this->magicLink->requested_at->format('d/m/Y H:i') . '] - Log in to '
Done, thanks

2024-02-21 10:43 UTC, jimleeder123 commented on app/Actions/MagicLinks/LoginAction.php
Renamed now that the points have been done

2024-02-21 11:03 UTC, jimleeder123 commented on tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
Done

2024-02-21 11:06 UTC, jimleeder123 commented on tests/Unit/Actions/MagicLinks/LoginActionTest.php
Done, it is now just one test in the class

2024-02-21 11:06 UTC, jimleeder123 commented on tests/Unit/Models/MagicLinkTest.php
Deleted

2024-02-21 11:41 UTC, gbuckingham89 commented on app/Actions/MagicLinks/LoginAction.php
> +        if ($magicLink->isValid($ipAddress)) {
Yeah I guess we should redirect to keep it user friendly.

I'd say redirect to the portal URL - that way if a user is still already logged in, thats good - and if they're not, the middleware / auth for the portal should redirect them to a generic login page.

2024-02-21 11:52 UTC, gbuckingham89 requested changes
I think that's looking much better - nice job on the refactoring :) 

Just a few small amends and some tests!

2024-02-21 11:52 UTC, gbuckingham89 commented on tests/Unit/Actions/MagicLinks/LoginActionTest.php
Test needs renaming to match the action, `MarkAsAuthenticatedTest`

2024-02-21 11:52 UTC, gbuckingham89 commented on tests/Unit/Actions/MagicLinks/LoginActionTest.php
> +        $this->assertNotNull($magicLink->authenticated_at);
If you add `$this->freezeSecond();` (which fakes the time, freezing it to "now") before the action is called, we can then assert that this timestamp is set to "now".

```php
$this->assertEquals(CarbonImmutable::now(), $magicLink->authenticated_at);
```

2024-02-21 11:52 UTC, gbuckingham89 commented on app/Http/Controllers/Web/AuthController.php
> +        Auth::login($user);
Shouldn't need this comment - a magic link should always have a user - I think the docblock comment in the MagicLink class is wrong.

We then just pass directly to the Auth too; `Auth::login($magicLink->user)`.

2024-02-21 11:52 UTC, gbuckingham89 commented on app/Http/Middleware/VerifyMagicLink.php
> +        }
This one looks good!

2024-02-21 11:52 UTC, gbuckingham89 commented on app/Http/Middleware/VerifyMagicLink.php
> +        }
Replace with a redirect to the portal.

2024-02-21 11:52 UTC, gbuckingham89 commented on app/Http/Middleware/VerifyMagicLink.php
> +        }
Replace with a redirect to the portal.

2024-02-21 11:52 UTC, gbuckingham89 commented on app/Http/Middleware/VerifyMagicLink.php
> +        }
Replace with a redirect to the portal.

2024-02-21 11:52 UTC, gbuckingham89 commented on tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
Can we add some more test cases in here;

- When he magic link has expired
- When the magic link has already been used 
- When the IP addresses don't match
- When the URL isn't signed

2024-02-21 11:52 UTC, gbuckingham89 commented on tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
> +    public function test_switches_already_authenticated_user_to_target_user(): void
Nice! 👌

2024-02-21 11:52 UTC, gbuckingham89 commented on tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
> +        $this->assertAuthenticated();
Assert authenticated as who?

2024-02-21 11:52 UTC, gbuckingham89 commented on tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
> +        $this->assertAuthenticated();
Assert authenticated as who?

2024-02-21 12:23 UTC, jimleeder123 commented on tests/Unit/Actions/MagicLinks/LoginActionTest.php
Done

2024-02-21 12:24 UTC, jimleeder123 commented on tests/Unit/Actions/MagicLinks/LoginActionTest.php
> +        $this->assertNotNull($magicLink->authenticated_at);
Done, works well thanks

2024-02-21 12:54 UTC, jimleeder123 commented on tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
> +        $this->assertAuthenticated();
Have changed to `AuthenticatedAs($magicLink->user)` since the user is made inside the `database/factories/MagicLinkFactory` file

2024-02-21 12:56 UTC, jimleeder123 commented on tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
> +        $this->assertAuthenticated();
Done same as other point

2024-02-21 13:04 UTC, jimleeder123 commented on app/Http/Middleware/VerifyMagicLink.php
> +        }
Done

2024-02-21 13:04 UTC, jimleeder123 commented on app/Http/Middleware/VerifyMagicLink.php
> +        }
Done

2024-02-21 13:04 UTC, jimleeder123 commented on app/Http/Middleware/VerifyMagicLink.php
> +        }
Done

2024-02-21 13:19 UTC, jimleeder123 commented on tests/Feature/Http/Web/AuthController/GetMagicLinkTest.php
All added

2024-02-21 13:36 UTC, gbuckingham89 commented on app/Http/Controllers/Web/AuthController.php
> +        Auth::login($user);
The `user_id` on a magic link isn't nullable in the database, so a MagucLink model will always be associated with a user. 

I don't think we'll go down the route of deleting users - at best I think we'd "anonymise" their data, never really deleting them.

2024-02-21 13:39 UTC, gbuckingham89 requested changes
Very almost there! Just one route name to change and I think we're good to go :)

2024-02-21 13:39 UTC, gbuckingham89 commented on routes/web.php
> +        ->name('portal');
I know its only a placeholder, but good to keep in the habit of having`.index` on the name of "index-y" routes.

2024-02-21 13:41 UTC, jimleeder123 commented on routes/web.php
> +        ->name('portal');
Done

2024-02-21 13:43 UTC, gbuckingham89 approved these changes
🚀

2024-02-21 13:47 UTC, merged