Error Pages UI
Yammayap/widgets.workplacefutures.com pull request #41
Opened 2024-02-23 13:50 UTC by jimleeder123

This is for the error pages HTML and text without styling. The error pages were generated via Laravel's default error page templates - https://laravel.com/docs/10.x/errors#custom-http-error-pages - with some customisations made. I also used the text from CtrlCloud 2's error pages for inspiration. There are `4xx.blade.php` and `5xx.blade.php` files for any errors not covered by the individual files.

There is no styling and we may come back here later when we have designs to change how the pages look. However, for now this is good and minimal.

2024-02-23 13:50 UTC, jimleeder123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Error pages UI](https://trello.com/c/GEsP4lJl/39-error-pages-ui)

2024-02-23 14:52 UTC, gbuckingham89 requested changes
Nice job with the back buttons, I like them!

We'll tidy up when we have a design, but depending on styling, we may need to be careful with the message - sometimes it's in `<p>` tags, sometimes not.

I know some of my comments may have been from the Laravel defaults, but need to be careful we don't "leak" things through exceptions.

2024-02-23 14:52 UTC, gbuckingham89 commented on resources/views/errors/403.blade.php
> +@section('message', __($exception->getMessage() ?: 'You don\'t have permission to access this page.'))
Can we remove the `$exception->getMessage()` - this might not be very user friendly, and worse, may contain sensitive info.

2024-02-23 14:52 UTC, gbuckingham89 commented on resources/views/errors/4xx.blade.php
> +@section('code', $exception->getStatusCode())
Probably best to avoid relying on the exception - this might not be very user friendly, and worse, may contain sensitive info.

2024-02-23 14:52 UTC, gbuckingham89 commented on resources/views/errors/4xx.blade.php
> +    <p>It seems we're experiencing some technical problems.</p>
If it's a 400 error, it's not us thats having problems - they've sent a bad request ;)

2024-02-23 14:52 UTC, gbuckingham89 commented on resources/views/errors/4xx.blade.php
Given the comments below, it might be better to just turn this file into a view for a `400 Bad Request` error rather than trying to be too clever.

2024-02-23 14:52 UTC, gbuckingham89 commented on resources/views/errors/503.blade.php
> +    <p>This portal is temporarily unavailable because we're currently performing maintenance on our systems.</p>
Not specially the portal, can we make it a bit more generic please. Maybe just "This website" ?

2024-02-23 14:52 UTC, gbuckingham89 commented on resources/views/errors/5xx.blade.php
Again, relying on the exception is risky. Maybe we can just get rid of this one, as we have the `500` view for most server side errors.

2024-02-23 14:52 UTC, gbuckingham89 commented on resources/views/errors/layout.blade.php
Nice and simple - perfect!

2024-02-23 16:25 UTC, jimleeder123 commented on resources/views/errors/403.blade.php
> +@section('message', __($exception->getMessage() ?: 'You don\'t have permission to access this page.'))
Done

2024-02-23 16:28 UTC, jimleeder123 commented on resources/views/errors/4xx.blade.php
> +    <p>It seems we're experiencing some technical problems.</p>
I will change "we're" to "there are" unless we want something better?

2024-02-23 16:30 UTC, jimleeder123 commented on resources/views/errors/4xx.blade.php
I'll change the title to Bad Request

2024-02-23 16:32 UTC, jimleeder123 commented on resources/views/errors/503.blade.php
> +    <p>This portal is temporarily unavailable because we're currently performing maintenance on our systems.</p>
I nicked this bit from Tower, I saw it was referencing the app in a string rather than using `config('app.name')` or similar so I guess there's a possibility that could cause an error in this situation hence I just used portal, website sounds better

2024-02-23 16:33 UTC, jimleeder123 commented on resources/views/errors/5xx.blade.php
I've changed the title to "Internal Server Error" on this file similar to what's been done on `4xx.blade.php`

2024-02-26 12:53 UTC, gbuckingham89 approved these changes
✅ Looks good!

2024-02-26 13:24 UTC, merged